ci: fix docs.rs build
With the latest release, the build failed with the following message:
```
[INFO] [stderr] warning: target filter specified, but no targets matched; this is a no-op
[INFO] [stderr]  Documenting rusqlite_migration v2.4.0 (/opt/rustwide/workdir)
[INFO] [stderr] error[E0557]: feature has been removed
[INFO] [stderr]   --> src/lib.rs:16:29
[INFO] [stderr]    |
[INFO] [stderr] 16 | #![cfg_attr(docsrs, feature(doc_auto_cfg))]
[INFO] [stderr]    |                             ^^^^^^^^^^^^ feature has been removed
[INFO] [stderr]    |
[INFO] [stderr]    = note: removed in 1.92.0; see <https://github.com/rust-lang/rust/pull/138907> for more information
[INFO] [stderr]    = note: merged into `doc_cfg`
[INFO] [stderr]
[INFO] [stderr] error: Compilation failed, aborting rustdoc
[INFO] [stderr]
[INFO] [stderr] For more information about this error, try `rustc --explain E0557`.
[INFO] [stderr] error: could not document `rusqlite_migration`
[INFO] running `Command { std: "docker" "inspect" "26826757a8ad458b8bbb5f243bced1ac8ce41d69fd58dad40c4fdc43f3305cbf", kill_on_drop: false }`
[INFO] running `Command { std: "docker" "rm" "-f" "26826757a8ad458b8bbb5f243bced1ac8ce41d69fd58dad40c4fdc43f3305cbf", kill_on_drop: false }`
[INFO] [stdout] 26826757a8ad458b8bbb5f243bced1ac8ce41d69fd58dad40c4fdc43f3305cbf
```
(from https://docs.rs/crate/rusqlite_migration/latest/builds/2835983)