chore: bump MSRV to 1.77.0
First, CI output first flagged `clap`:

```
error: package `clap v4.5.13` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.70.0
Either upgrade to rustc 1.74 or newer, or use
cargo update -p clap@4.5.13 --precise ver
where `ver` is the latest version of `clap` supporting rustc 1.70.0
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 101
```
Then rusqlite 0.32 uses a ructc-feature `c_literal` [commit], which has
been stablized in 1.77.0.

Second, Rust 1.77.0, went out almost 6 months ago at this point, so we
are not going to require a very recent rust version.

Note: Reworded based on this thread: https://github.com/cljoly/rusqlite_migration/pull/181#discussion_r1704718325

[commit] https://github.com/rusqlite/rusqlite/commit/ed7434e95852f14e3a8683927a136e4daa8ffa9e